dist: trusty
language: php
php:
  - '7.0'
services:
  - mysql

before_install:
  - echo "Installing prerequisites..."
  - sudo apt-get update -qq
  - sudo apt-get install -y bibutils zip

  # configure PHP with yaz/xsl/intl extensions

#  - sudo add-apt-repository -y ppa:ondrej/php && sudo apt-get update && sudo apt-get install -y php7.0-xsl php7.0-intl; fi  
#  - sudo apt-get install -y yaz libyaz4-dev
#  - pear channel-update pear.php.net && yes $'\n' | pecl install yaz && pear install Structures_LinkedList-0.2.2 && pear install File_MARC 
#  - sudo service apache2 restart
#  - if php -i | grep yaz --quiet && echo '<?php exit(function_exists("yaz_connect")?0:1);' | php ; then echo "YAZ is installed"; else echo "YAZ installation failed"; exit 1; fi;

install:
  - echo "travis_fold:start:npm_install"
  - echo "Installing dependencies..."
  - [[ -f package-lock.json ]] && rm package-lock.json
  - rm -rf node_modules
  - npm install npm@latest -g
  - npm install
  - npm link mocha
  - echo "travis_fold:end:npm_install"
  - echo "Building Bibliograph..."
  - pushd src/client/bibliograph
  - qx compile ../../../build-env/travis/compile.json --all-targets 
  - popd
  - echo "Installation scripts finished successufully."

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS tests;'
  
script:
  - npm test
